# Generated by Django 3.1.7 on 2021-03-16 14:12

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('team', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='team.team')),
            ],
        ),
    ]
