# Generated by Django 3.1.7 on 2021-03-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20210316_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
