# Generated by Django 3.1.7 on 2021-03-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('asset', '0003_auto_20210316_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier'),
        ),
    ]
