# Generated by Django 3.1.7 on 2021-03-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210317_0952'),
        ('asset', '0003_auto_20210316_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.room'),
        ),
    ]
