# Generated by Django 3.1.7 on 2021-03-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_room'),
        ('asset', '0004_asset_supplier'),
    ]

    operations = [
    ]
